/**

  This file contains the Backus-Naur grammar for the Pascal style language
  used to perform user actions to test an applications behaviour.

  @Author  David Hoyle
  @Version 1.394
  @Date    18 Jun 2026

  @usesemicolon
  @license

    GUI Tester is a Win64 GUI application in which you can write statements
    to mimic a users interaction with an application and test that certain
    operations perform as expected.
    
    Copyright (C) 2026  David Hoyle (https://github.com/DGH2112/GUITester/)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

**/
<Goal>                ::= <Statements>;

<Statements>          ::= <Statement>*;

<Statement>           ::= ( <Launch>              |
                            <WaitForIdle>         |
                            <TestClass>           |
                            <SendKeys>            |
                            <WaitForWindow>       |
                            <Wait>                |
                            <CheckProcessEnd>     |
                            <BringToFront>        |
                            <PositionWindow>      |
                            <ListWindows>         |
                            <ListALLChildWindows> |
                            <ListChildWindows>    |
                            <ListTabOrder>
                      ) ';';

<Launch>              ::= 'LAUNCH' '(' <Executable> ',' <Directory> ',' <CommandLine> ')';

<Executable>          ::= <StringLiteral>;
                      
<Directory>           ::= <StringLiteral>;

<CommandLine>         ::= <StringLiteral>;

<WaitForIdle>         ::= 'WAITFORIDLE' '(' <IntegerNumber> ')';
                      
<TestClass>           ::= 'TESTCLASS' '(' <StringLiteral> ',' <StringLiteral> ',' <IntegerNumber> ')';

<SendKeys>            ::= 'SENDKEYS' '('
                        <StringLiteral> ','
                        '[' [ <StringList> ] ']' ','
                            ( <StringLiteral> | '[' <Identifier> ( ',' <Identifier>)* ']' ) ','
                        <IntegerNumber>
                      ')';
                      
<WaitForWindow>       ::= 'WAITFORWINDOW' '(' <StringLiteral> ',' <IntegerNumber> ')';

<Wait>                ::= 'WAIT' '(' <IntegerNumber> ')';

<CheckProcessEnd>     ::= 'CHECKPROCESSEND' '(' <IntegerNumber> ')';
                      
<BringToFront>        ::= 'BRINGTOFRONT' '(' <StringLiteral> ')';

<PositionWindow>      ::= 'POSITIONWINDOW' '(' <StringLiteral> ',' <IntegerNumber> ',' <IntegerNumber> ','
                                           <IntegerNumber> ',' <IntegerNumber> ')';

<ListWindows>         ::= 'LISTWINDOWS' '(' <StringLiteral> ' )';                                           

<ListALLChildWindows> ::= 'LISTALLCHILDWINDOWS' '(' <StringLiteral> ' )';

<ListChildWindows>    ::= 'LISTCHILDWINDOWS' '(' <StringLiteral> ' )';

<ListTabOrder>        ::= 'LISTTABORDER' '(' <StringLiteral> [ ',' <StringLiteral> ] ')';

<StringLiteral>       ::= '''' (#32..#127)* '''';

<StringList>          ::= ( <StringLiteral> ( ',' <StringLiteral> ) );

<IntegerNumber>       ::= ( <Digit> )*;

<Alpha>               ::= 'a'..'z' | 'A'..'Z' | '_';

<Digit>               ::= '0'..'9';

<Identifier>          ::= <Alpha> ( <Alpha> | <Digit> )*;

